"""Guard against drift between the generators and their committed artifacts.

`trtcheck/data/operator_matrix.json` and `docs/operators/*.md` are generated by
`tools/build_operator_matrix.py` and `tools/build_operator_docs.py`. If someone
hand-edits a committed artifact (or edits the generator without regenerating),
the two silently diverge. These tests fail when that happens, with a clear hint
to rerun the generator.
"""

from __future__ import annotations

import json
from pathlib import Path

from tools.build_operator_docs import render_index, render_operator
from tools.build_operator_matrix import build_matrix, render_matrix_json

_REPO = Path(__file__).resolve().parent.parent
_MATRIX_FILE = _REPO / "trtcheck" / "data" / "operator_matrix.json"
_DOCS_DIR = _REPO / "docs" / "operators"


def test_committed_matrix_matches_generator() -> None:
    """operator_matrix.json must equal build_operator_matrix.py's output."""
    expected = render_matrix_json(build_matrix())
    actual = _MATRIX_FILE.read_text()
    assert actual == expected, (
        "trtcheck/data/operator_matrix.json is out of sync with "
        "tools/build_operator_matrix.py. Rerun: python tools/build_operator_matrix.py"
    )


def test_committed_operator_docs_match_generator() -> None:
    """Every docs/operators/*.md page must equal build_operator_docs.py's output."""
    matrix = json.loads(_MATRIX_FILE.read_text())
    versions = matrix["target_trt_versions"]
    operators = matrix["operators"]

    for name, entry in operators.items():
        page = _DOCS_DIR / f"{name}.md"
        assert page.exists(), f"missing docs page for {name}; rerun build_operator_docs.py"
        expected = render_operator(name, entry, versions=versions)
        assert page.read_text() == expected, (
            f"docs/operators/{name}.md is out of sync with the generator. "
            "Rerun: python tools/build_operator_docs.py"
        )

    index = _DOCS_DIR / "index.md"
    assert index.read_text() == render_index(
        matrix
    ), "docs/operators/index.md is out of sync. Rerun: python tools/build_operator_docs.py"


def test_no_stale_or_missing_operator_pages() -> None:
    """The set of committed .md pages must be exactly operators + index."""
    matrix = json.loads(_MATRIX_FILE.read_text())
    expected = {f"{name}.md" for name in matrix["operators"]} | {"index.md"}
    committed = {p.name for p in _DOCS_DIR.glob("*.md")}
    assert committed == expected, (
        f"docs/operators/ pages drifted. Missing: {expected - committed}; "
        f"stale: {committed - expected}. Rerun build_operator_docs.py."
    )
